import { describe, expect, it } from 'vitest'
import { fireEvent, render, screen } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import ImageConverterWidget from './ImageConverterWidget'

const PNG_HEADER = [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0x00, 0x00, 0x00, 0x0d]

function imageFile(name: string, header: number[], type = ''): File {
  return new File([new Uint8Array(header)], name, { type })
}

/** jsdom builds no real DataTransfer, so the drop event carries the
 * minimum shape the widget reads off it. */
function dropFile(file: File) {
  fireEvent.drop(screen.getByText(/drop an image here/i), { dataTransfer: { files: [file] } })
}

/** The badge reporting what the *source* was detected as. Queried by its
 * label rather than by its text, because the target-format buttons carry
 * the same format names: a bare `findByText('PNG')` matches the PNG button
 * the moment a file is dropped, and so passes before detection has even
 * run. */
function detectedFormat() {
  return screen.findByLabelText('Detected source format')
}

describe('ImageConverterWidget', () => {
  it('starts on an empty drop zone', () => {
    render(<ImageConverterWidget instanceId="test" mode="grid" />)
    expect(screen.getByText(/drop an image here/i)).toBeInTheDocument()
    expect(screen.queryByRole('slider')).not.toBeInTheDocument()
  })

  it('detects the source format of a dropped file from its bytes, not its name', async () => {
    render(<ImageConverterWidget instanceId="test" mode="grid" />)

    dropFile(imageFile('mislabelled.jpg', PNG_HEADER))

    expect(await detectedFormat()).toHaveTextContent('PNG')
    expect(screen.getByText('mislabelled.jpg')).toBeInTheDocument()
  })

  it('detects a format even when the browser reports no MIME type', async () => {
    render(<ImageConverterWidget instanceId="test" mode="grid" />)

    dropFile(
      imageFile(
        'shot',
        [...'GIF89a'].map((char) => char.charCodeAt(0)),
      ),
    )

    expect(await screen.findByText('GIF')).toBeInTheDocument()
  })

  it('reports a file it cannot recognize as an image', async () => {
    render(<ImageConverterWidget instanceId="test" mode="grid" />)

    dropFile(
      imageFile(
        'notes.txt',
        [...'hello there'].map((char) => char.charCodeAt(0)),
        'text/plain',
      ),
    )

    expect(await screen.findByText(/could not recognize notes\.txt/i)).toBeInTheDocument()
    expect(await detectedFormat()).toHaveTextContent('Unknown')
  })

  it('detects an SVG whose root tag sits past a long prologue', async () => {
    render(<ImageConverterWidget instanceId="test" mode="grid" />)

    const prologue =
      '<?xml version="1.0" encoding="UTF-8" standalone="no"?>\n' +
      '<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">\n' +
      '<!-- Generated by a drawing program that likes long banners -->\n'
    const svg = `${prologue}<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 10"></svg>`
    expect(prologue.length).toBeGreaterThan(64)

    dropFile(
      imageFile(
        'logo.svg',
        [...svg].map((char) => char.charCodeAt(0)),
        'image/svg+xml',
      ),
    )

    expect(await detectedFormat()).toHaveTextContent('SVG')
  })

  it('does not take an HTML page with an inline icon for an image', async () => {
    render(<ImageConverterWidget instanceId="test" mode="grid" />)

    const html = '<!doctype html>\n<html><body><svg viewBox="0 0 8 8"><rect /></svg></body></html>'
    dropFile(
      imageFile(
        'page.html',
        [...html].map((char) => char.charCodeAt(0)),
        'text/html',
      ),
    )

    expect(await screen.findByText(/could not recognize page\.html/i)).toBeInTheDocument()
  })

  it('offers the encodable target formats and a quality slider only for lossy ones', async () => {
    const user = userEvent.setup()
    render(<ImageConverterWidget instanceId="test" mode="grid" />)

    dropFile(imageFile('photo.png', PNG_HEADER))
    await detectedFormat()

    // PNG is the default target and is lossless.
    expect(screen.queryByRole('slider')).not.toBeInTheDocument()

    await user.click(screen.getByRole('button', { name: 'JPEG' }))
    expect(screen.getByRole('slider')).toHaveValue('90')

    await user.click(screen.getByRole('button', { name: 'PNG' }))
    expect(screen.queryByRole('slider')).not.toBeInTheDocument()
  })

  it('goes back to the drop zone when the image is removed', async () => {
    const user = userEvent.setup()
    render(<ImageConverterWidget instanceId="test" mode="grid" />)

    dropFile(imageFile('photo.png', PNG_HEADER))
    await detectedFormat()

    await user.click(screen.getByRole('button', { name: /remove image/i }))

    expect(screen.getByText(/drop an image here/i)).toBeInTheDocument()
    expect(screen.queryByText('photo.png')).not.toBeInTheDocument()
  })

  it('keeps the chosen target format across a remount of the same instance', async () => {
    const user = userEvent.setup()
    const { unmount } = render(<ImageConverterWidget instanceId="test" mode="grid" />)

    dropFile(imageFile('photo.png', PNG_HEADER))
    await detectedFormat()
    await user.click(screen.getByRole('button', { name: 'WebP' }))
    unmount()

    render(<ImageConverterWidget instanceId="test" mode="grid" />)
    expect(await screen.findByRole('button', { name: 'WebP' })).toHaveAttribute('aria-pressed', 'true')
  })
})
